definitions:
  models.User:
    description: User model
    properties:
      city:
        type: string
      country:
        type: string
      date_of_birth:
        type: string
      email:
        type: string
      first_name:
        type: string
      gender:
        description: gorm.Model // Embedding the gorm.Model for ID, CreatedAt, UpdatedAt,
          and DeletedAt fields
        type: string
      job:
        type: string
      last_name:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      password:
        type: string
      phone:
        type: string
      profile_picture:
        type: string
      state:
        type: string
      street:
        type: string
      zipcode:
        type: string
    type: object
  types.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Logs in a user and returns a JWT token
      parameters:
      - description: Login Request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: JWT Token
          schema:
            type: string
        "400":
          description: Invalid data request
          schema:
            type: string
        "401":
          description: Invalid email or password
          schema:
            type: string
      summary: User login
      tags:
      - user
  /users/{userID}:
    get:
      consumes:
      - application/json
      description: Retrieves a user by their ID
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User object
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Invalid user id
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get user by ID
      tags:
      - user
swagger: "2.0"
